### ISSUE TITLE
postgresql_server_id is not used consistently

### ISSUE THREAD

**Issue by igalic** [2ndquadrant-it/puppet-barman#24]
when setting `postgresql_server_id` through `barman::postgres` it's not used consistently, the exported resource will still be `name`d `$::hostname`, and so barman will be expecting its wal to show up in `/var/lib/barman/$hostname/incoming/` rather than in `/var/lib/barman/$postgresql_server_id/incoming/`

**Comment by gbroccolo** [comment]
Thanks. I modified the postgres.pp manifest and now the postgresql_server_id is consistently used in the exported resource. Its default value is $::hostname, but a different value can be set e.g. through hiera file.

I already committed the modifications in the master branch. I close this issue.
