### ISSUE TITLE
Allow configuring $retention_policy in barman::postgres

### ISSUE THREAD

**Issue by dnlsng** [2ndquadrant-it/puppet-barman#25]
It would be nice to be able to configure $retention_policy from barman::postgres and then have that class pass it to barman::server. This looks like it would be a easy addition since barman::server already accepts the $retention_policy parameter. I don't mind submitting a pull request if that is ok.

**Comment by fcanovai** [comment]
fixed in https://github.com/2ndquadrant-it/puppet-barman/commit/c56cf5f9f06d2f05360dd1d12d98b56c935f39ff
