### ISSUE TITLE
On Solaris 11, postgres_key fact prints errors

### ISSUE THREAD

**Issue by dnlsng** [2ndquadrant-it/puppet-barman#27]
On a Solaris 11 host configured by puppet, pluginsync will pull down the barman_key.rb fact and when it tries to process the postgres_key fact I get:

    root@solaris11:~# facter -p postgres_key
    Could not create directory '//.ssh'.
    open //.ssh/id_rsa failed: No such file or directory.
    root@solaris11:~#

This is due to Solaris's entry in passwd for postgres looking like this:

    postgres:x:90:90:PostgreSQL Reserved UID:/:/usr/bin/pfksh

Since this module is only supported on Linux, perhaps a quick fix for this is to confine the facts to :kernel => 'Linux' ?

**Comment by fcanovai** [comment]
#28 has been merged, I'm closing this issue
