### ISSUE TITLE
puppet parser validate fails on barman::settings

### ISSUE THREAD

**Issue by derjohn** [2ndquadrant-it/puppet-barman#30]
Hello,
in class barman::settings there is a duplicate declaration, which makes puppet parser validate fail:

```
class barman::settings (
...
  $pre_backup_script       = false,
  $post_backup_script      = false,
...
  $basebackup_retry_sleep  = false,
  $pre_backup_script       = false,   <==== !!
  $post_backup_script      = false    <==== !!
```

**Comment by darrylkuhn** [comment]
Any chance to get https://github.com/2ndquadrant-it/puppet-barman/pull/32 merged? Seems to resolve the issue for me in puppet 4.4.2

**Comment by georgehansper** [comment]
We're encountering the same problem

**Comment by fcanovai** [comment]
#32 has been merged. I'm closing this issue.
