### ISSUE TITLE
New release on the forge?

### ISSUE THREAD

**Issue by saz** [2ndquadrant-it/puppet-barman#35]
Any chance for a new release on the puppet forge?

**Comment by Behner** [comment]
Please?

**Comment by fcanovai** [comment]
Greetings,

We are currently about to merge costela's pull request  (#37). 

As soon as that is done, a new release of the module will be issued on puppetforge within a few days.

Best regards,

Francesco

**Comment by mnencia** [comment]
The #37 pull request has benn merged. Now we will proceed with the release.

**Comment by mnencia** [comment]
The version 2.0.0 has been released.
