### ISSUE TITLE
custom_lines deprecated, but no alternative

### ISSUE THREAD

**Issue by costela** [2ndquadrant-it/puppet-barman#36]
Currently the `custom_lines` parameter is marked as deprecated, but there's no alternative for configuring - for instance - `streaming_archiver`.
Would you accept a PR extending `barman::server` to support all current relevant settings?

**Comment by mnencia** [comment]
Of course, we are open to pull requests.

**Comment by costela** [comment]
I've created PR #37 to address this issue (plus a couple minor test fixes). Could someone please take a look?
